
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8" /><meta name="generator" content="Docutils 0.17.1: http://docutils.sourceforge.net/" />

    <title>google.auth.exceptions module &#8212; google-auth 1.30.0 documentation</title>
    <link rel="stylesheet" href="../_static/alabaster.css" type="text/css" />
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    <script id="documentation_options" data-url_root="../" src="../_static/documentation_options.js"></script>
    <script src="../_static/jquery.js"></script>
    <script src="../_static/underscore.js"></script>
    <script src="../_static/doctools.js"></script>
    <script src="../_static/language_data.js"></script>
    <link rel="index" title="Index" href="../genindex.html" />
    <link rel="search" title="Search" href="../search.html" />
    <link rel="next" title="google.auth.external_account module" href="google.auth.external_account.html" />
    <link rel="prev" title="google.auth.environment_vars module" href="google.auth.environment_vars.html" />
   
  <link rel="stylesheet" href="../_static/custom.css" type="text/css" />
  
  
  <meta name="viewport" content="width=device-width, initial-scale=0.9, maximum-scale=0.9" />

  </head><body>
  

    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          

          <div class="body" role="main">
            
  <section id="module-google.auth.exceptions">
<span id="google-auth-exceptions-module"></span><h1>google.auth.exceptions module<a class="headerlink" href="#module-google.auth.exceptions" title="Permalink to this headline">¶</a></h1>
<p>Exceptions used in the google.auth package.</p>
<dl class="exception">
<dt id="google.auth.exceptions.GoogleAuthError">
<em class="property">exception </em><code class="sig-name descname">GoogleAuthError</code><a class="reference internal" href="../_modules/google/auth/exceptions.html#GoogleAuthError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#google.auth.exceptions.GoogleAuthError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3.5/library/exceptions.html#Exception" title="(in Python v3.5)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<p>Base class for all google.auth errors.</p>
<dl class="method">
<dt id="google.auth.exceptions.GoogleAuthError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#google.auth.exceptions.GoogleAuthError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="google.auth.exceptions.TransportError">
<em class="property">exception </em><code class="sig-name descname">TransportError</code><a class="reference internal" href="../_modules/google/auth/exceptions.html#TransportError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#google.auth.exceptions.TransportError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#google.auth.exceptions.GoogleAuthError" title="google.auth.exceptions.GoogleAuthError"><code class="xref py py-class docutils literal notranslate"><span class="pre">google.auth.exceptions.GoogleAuthError</span></code></a></p>
<p>Used to indicate an error occurred during an HTTP request.</p>
<dl class="method">
<dt id="google.auth.exceptions.TransportError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#google.auth.exceptions.TransportError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="google.auth.exceptions.RefreshError">
<em class="property">exception </em><code class="sig-name descname">RefreshError</code><a class="reference internal" href="../_modules/google/auth/exceptions.html#RefreshError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#google.auth.exceptions.RefreshError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#google.auth.exceptions.GoogleAuthError" title="google.auth.exceptions.GoogleAuthError"><code class="xref py py-class docutils literal notranslate"><span class="pre">google.auth.exceptions.GoogleAuthError</span></code></a></p>
<p>Used to indicate that an refreshing the credentials’ access token
failed.</p>
<dl class="method">
<dt id="google.auth.exceptions.RefreshError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#google.auth.exceptions.RefreshError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="google.auth.exceptions.UserAccessTokenError">
<em class="property">exception </em><code class="sig-name descname">UserAccessTokenError</code><a class="reference internal" href="../_modules/google/auth/exceptions.html#UserAccessTokenError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#google.auth.exceptions.UserAccessTokenError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#google.auth.exceptions.GoogleAuthError" title="google.auth.exceptions.GoogleAuthError"><code class="xref py py-class docutils literal notranslate"><span class="pre">google.auth.exceptions.GoogleAuthError</span></code></a></p>
<p>Used to indicate <code class="docutils literal notranslate"><span class="pre">gcloud</span> <span class="pre">auth</span> <span class="pre">print-access-token</span></code> command failed.</p>
<dl class="method">
<dt id="google.auth.exceptions.UserAccessTokenError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#google.auth.exceptions.UserAccessTokenError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="google.auth.exceptions.DefaultCredentialsError">
<em class="property">exception </em><code class="sig-name descname">DefaultCredentialsError</code><a class="reference internal" href="../_modules/google/auth/exceptions.html#DefaultCredentialsError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#google.auth.exceptions.DefaultCredentialsError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#google.auth.exceptions.GoogleAuthError" title="google.auth.exceptions.GoogleAuthError"><code class="xref py py-class docutils literal notranslate"><span class="pre">google.auth.exceptions.GoogleAuthError</span></code></a></p>
<p>Used to indicate that acquiring default credentials failed.</p>
<dl class="method">
<dt id="google.auth.exceptions.DefaultCredentialsError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#google.auth.exceptions.DefaultCredentialsError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="google.auth.exceptions.MutualTLSChannelError">
<em class="property">exception </em><code class="sig-name descname">MutualTLSChannelError</code><a class="reference internal" href="../_modules/google/auth/exceptions.html#MutualTLSChannelError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#google.auth.exceptions.MutualTLSChannelError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#google.auth.exceptions.GoogleAuthError" title="google.auth.exceptions.GoogleAuthError"><code class="xref py py-class docutils literal notranslate"><span class="pre">google.auth.exceptions.GoogleAuthError</span></code></a></p>
<p>Used to indicate that mutual TLS channel creation is failed, or mutual
TLS channel credentials is missing or invalid.</p>
<dl class="method">
<dt id="google.auth.exceptions.MutualTLSChannelError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#google.auth.exceptions.MutualTLSChannelError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="google.auth.exceptions.ClientCertError">
<em class="property">exception </em><code class="sig-name descname">ClientCertError</code><a class="reference internal" href="../_modules/google/auth/exceptions.html#ClientCertError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#google.auth.exceptions.ClientCertError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#google.auth.exceptions.GoogleAuthError" title="google.auth.exceptions.GoogleAuthError"><code class="xref py py-class docutils literal notranslate"><span class="pre">google.auth.exceptions.GoogleAuthError</span></code></a></p>
<p>Used to indicate that client certificate is missing or invalid.</p>
<dl class="method">
<dt id="google.auth.exceptions.ClientCertError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#google.auth.exceptions.ClientCertError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="google.auth.exceptions.OAuthError">
<em class="property">exception </em><code class="sig-name descname">OAuthError</code><a class="reference internal" href="../_modules/google/auth/exceptions.html#OAuthError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#google.auth.exceptions.OAuthError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#google.auth.exceptions.GoogleAuthError" title="google.auth.exceptions.GoogleAuthError"><code class="xref py py-class docutils literal notranslate"><span class="pre">google.auth.exceptions.GoogleAuthError</span></code></a></p>
<p>Used to indicate an error occurred during an OAuth related HTTP
request.</p>
<dl class="method">
<dt id="google.auth.exceptions.OAuthError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#google.auth.exceptions.OAuthError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="exception">
<dt id="google.auth.exceptions.ReauthFailError">
<em class="property">exception </em><code class="sig-name descname">ReauthFailError</code><span class="sig-paren">(</span><em class="sig-param">message=None</em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/google/auth/exceptions.html#ReauthFailError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#google.auth.exceptions.ReauthFailError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#google.auth.exceptions.RefreshError" title="google.auth.exceptions.RefreshError"><code class="xref py py-class docutils literal notranslate"><span class="pre">google.auth.exceptions.RefreshError</span></code></a></p>
<p>An exception for when reauth failed.</p>
<dl class="method">
<dt id="google.auth.exceptions.ReauthFailError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#google.auth.exceptions.ReauthFailError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

</section>


          </div>
          
        </div>
      </div>
      <div class="sphinxsidebar" role="navigation" aria-label="main navigation">
        <div class="sphinxsidebarwrapper">
<h1 class="logo"><a href="../index.html">google-auth</a></h1>



<p class="blurb">Google Auth Library for Python</p>




<p>
<iframe src="https://ghbtns.com/github-btn.html?user=GoogleCloudPlatform&repo=google-auth-library-python&type=watch&count=true&size=large&v=2"
  allowtransparency="true" frameborder="0" scrolling="0" width="200px" height="35px"></iframe>
</p>





    

<p>
<a class="badge" href="https://travis-ci.org/GoogleCloudPlatform/google-auth-library-python">
    <img
        alt="https://secure.travis-ci.org/GoogleCloudPlatform/google-auth-library-python.svg?branch=master"
        src="https://secure.travis-ci.org/GoogleCloudPlatform/google-auth-library-python.svg?branch=master"
    />
</a>
</p>


<h3>Navigation</h3>
<ul class="current">
<li class="toctree-l1"><a class="reference internal" href="../user-guide.html">User Guide</a></li>
<li class="toctree-l1 current"><a class="reference internal" href="modules.html">Reference</a><ul class="current">
<li class="toctree-l2 current"><a class="reference internal" href="google.html">google package</a></li>
</ul>
</li>
</ul>

<div class="relations">
<h3>Related Topics</h3>
<ul>
  <li><a href="../index.html">Documentation overview</a><ul>
  <li><a href="modules.html">google</a><ul>
  <li><a href="google.html">google package</a><ul>
  <li><a href="google.auth.html">google.auth package</a><ul>
      <li>Previous: <a href="google.auth.environment_vars.html" title="previous chapter">google.auth.environment_vars module</a></li>
      <li>Next: <a href="google.auth.external_account.html" title="next chapter">google.auth.external_account module</a></li>
  </ul></li>
  </ul></li>
  </ul></li>
  </ul></li>
</ul>
</div>
<div id="searchbox" style="display: none" role="search">
  <h3 id="searchlabel">Quick search</h3>
    <div class="searchformwrapper">
    <form class="search" action="../search.html" method="get">
      <input type="text" name="q" aria-labelledby="searchlabel" />
      <input type="submit" value="Go" />
    </form>
    </div>
</div>
<script>$('#searchbox').show(0);</script>
        </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="footer">
      &copy;2016, Google, Inc..
      
      |
      Powered by <a href="http://sphinx-doc.org/">Sphinx 2.4.4</a>
      &amp; <a href="https://github.com/bitprophet/alabaster">Alabaster 0.7.12</a>
      
      |
      <a href="../_sources/reference/google.auth.exceptions.rst.txt"
          rel="nofollow">Page source</a>
    </div>

    
    <a href="https://github.com/GoogleCloudPlatform/google-auth-library-python" class="github">
        <img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub"  class="github"/>
    </a>
    

    
  </body>
</html>